cascade:
  # Configure blog posts
  - _target:
      path: /post/**
    pager: true
    editable: false
    reading_time: true
    commentable: true
    show_related: true
    show_breadcrumb: true
    share: true
    header:
      navbar:
        enable: false